### PR TITLE
chore: this adds in the CoverageFund's address to the readme

### PR DESCRIPTION
**Pull request by mischat**
## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/liquid-collective/liquid-collective-protocol/pulls) for the same update/change?
- [x] Have you assigned this PR to yourself?
- [x] Have you added at least 1 reviewer?
- [x] Have you updated the official documentation?
- [x] Have you added sufficient documentation in your code?
- [ ] Have you added relevant tests to the official test suite?

## Pull Request Type

- [ ] 💫 New Feature (Breaking Change)
- [ ] 💫 New Feature (Non-breaking Change)
- [ ] 🛠️ Bug fix (Non-breaking Change: Fixes an issue)
- [x] 🕹️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)

## Testing

- [ ] Have you tested this code with the official test suite?
- [ ] Have you tested this code manually?

### CODE REVIEW

**Review by cebidhem — DISMISSED** [review]
LGTM 🚀

**Review by iamsahu — CHANGES_REQUESTED** [review]
The link to `CoverageFund` is broken. Apart from that it is good to go.

**Review by iamsahu — APPROVED** [review]
LGTM 🚀

**Review by cebidhem — APPROVED** [review]
LGTM 🚀

**Pull request merged**
