### PR TITLE
Removed redundant return variable

### PR DESCRIPTION
**Pull request by iamsahu**
## Description

During refactoring a return variable was added which was redundant and is removed in this PR.

## Notice
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/liquid-collective/liquid-collective-protocol/pulls) for the same update/change?
- [x] Have you assigned this PR to yourself?
- [x] Have you added at least 1 reviewer?
- [x] Have you updated the official documentation?
- [x] Have you added sufficient documentation in your code?
- [ ] Have you added relevant tests to the official test suite?

## Pull Request Type

- [ ] 💫 New Feature (Breaking Change)
- [ ] 💫 New Feature (Non-breaking Change)
- [ ] 🛠️ Bug fix (Non-breaking Change: Fixes an issue)
- [x] 🕹️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)

## Testing

- [x] Have you tested this code with the official test suite?
- [ ] Have you tested this code manually?

### CODE REVIEW

**Review by koderholic — COMMENTED** [review]
@iamsahu, Would it be a good idea to update the function name to better reflect its purpose, since this function updates the picked count of validators for each operator and does not return any values?

A suggested name would be:

_updateCountOfPickedValidatorsForEachOperator

**Comment by iamsahu** [comment]
> @iamsahu, Would it be a good idea to update the function name to better reflect its purpose, since this function updates the picked count of validators for each operator and does not return any values?
> 
> A suggested name would be:
> 
> _updateCountOfPickedValidatorsForEachOperator

That sounds good to me. Will push the change

**Review by koderholic — APPROVED** [review]
LGTM

**Review by mischat — APPROVED** [review]
LGTM too

**Pull request merged**
