### PR TITLE
Removed admin modifier on pause in TUPProxy (ETH-1621)

### PR DESCRIPTION
**Pull request by iamsahu**
## Description

Removed admin modifier on pause function in TUPProxy

## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/liquid-collective/liquid-collective-protocol/pulls) for the same update/change?
- [x] Have you assigned this PR to yourself?
- [x] Have you added at least 1 reviewer?
- [ ] Have you updated the official documentation?
- [ ] Have you added sufficient documentation in your code?
- [ ] Have you added relevant tests to the official test suite?

## Pull Request Type

- [ ] 💫 New Feature (Breaking Change)
- [ ] 💫 New Feature (Non-breaking Change)
- [x] 🛠️ Bug fix (Non-breaking Change: Fixes an issue)
- [ ] 🕹️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)

### CODE REVIEW

**Comment by mischat** [comment]
it feels like we should close this PR and ditch it ?

**Comment by iamsahu** [comment]
> @iamsahu I thought we said we wouldn't fix this one, as it is in the Proxy, and updating this would end up changing the River address, as well as the ERC20 address and that is something that we didn't want to do?
> 
> All the data is onchain anyways, publicly, people can observe the event emitted when paused.

You are absolutely right. We had decided to update this so that in future deployments we would not have this, we won't be deploying this in near future.

I still feel that this should be included for the future.

**Comment by mischat** [comment]
> > @iamsahu I thought we said we wouldn't fix this one, as it is in the Proxy, and updating this would end up changing the River address, as well as the ERC20 address and that is something that we didn't want to do?
> > All the data is onchain anyways, publicly, people can observe the event emitted when paused.
> 
> You are absolutely right. We had decided to update this so that in future deployments we would not have this, we won't be deploying this in near future.
> 
> I still feel that this should be included for the future.

Makes sense ...

**Review by mischat — APPROVED** [review]
LGTM

**Pull request merged**
